services:
  app:
    build: .
    container_name: typescript-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${DB_HOST}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
