version: "3.8"
services:
  app:
    image: node:18.20.4
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env.production

    command: sh -c "npm install && npm run start"
    restart: alwaysdocker
